--DROP TABLE EQUIPO_HAS_GRUPO;
--DROP TABLE EQUIPO;
--DROP TABLE GRUPO;


CREATE TABLE EQUIPO (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL UNIQUE,
    BOMBO NUMBER(1,0)
);
CREATE TABLE GRUPO (
    ID NUMBER PRIMARY KEY,
    LETRA VARCHAR(1) NOT NULL
);

CREATE TABLE EQUIPO_HAS_GRUPO(
    IDEQUIPO NUMBER UNIQUE,
    IDGRUPO NUMBER,
    PRIMARY KEY(IDEQUIPO,IDGRUPO),
    FOREIGN KEY (IDEQUIPO) REFERENCES EQUIPO(ID),
    FOREIGN KEY (IDGRUPO) REFERENCES GRUPO(ID)
);

INSERT INTO GRUPO VALUES (1,'A');
INSERT INTO GRUPO VALUES (2,'B');
INSERT INTO GRUPO VALUES (3,'C');
INSERT INTO GRUPO VALUES (4,'D');
INSERT INTO GRUPO VALUES (5,'E');
INSERT INTO GRUPO VALUES (6,'F');
INSERT INTO GRUPO VALUES (7,'G');
INSERT INTO GRUPO VALUES (8,'H');

-- BOMBO 1 --
INSERT INTO EQUIPO VALUES (1,'FC Barcelona',1);
INSERT INTO EQUIPO VALUES (2,'Bayern de Múnich',1);
INSERT INTO EQUIPO VALUES (3,'Juventus',1);
INSERT INTO EQUIPO VALUES (4,'Manchester City',1);
INSERT INTO EQUIPO VALUES (5,'PSG',1);
INSERT INTO EQUIPO VALUES (6,'Liverpool',1);
INSERT INTO EQUIPO VALUES (7,'Chelsea',1);
INSERT INTO EQUIPO VALUES (8,'Zenit',1);

-- BOMBO 2 --
INSERT INTO EQUIPO VALUES (9,'Real Madrid',2);
INSERT INTO EQUIPO VALUES (10,'Atlético de Madrid',2);
INSERT INTO EQUIPO VALUES (11,'Borussia Dortmund',2);
INSERT INTO EQUIPO VALUES (12,'Nápoles',2);
INSERT INTO EQUIPO VALUES (13,'Shakhtar Donetsk',2);
INSERT INTO EQUIPO VALUES (14,'Tottenham',2);
INSERT INTO EQUIPO VALUES (15,'Benfica',2);
INSERT INTO EQUIPO VALUES (16,'Ajax',2);

-- BOMBO 3 --
INSERT INTO EQUIPO VALUES (17,'Lyon',3);
INSERT INTO EQUIPO VALUES (18,'Bayer Leverkusen',3);
INSERT INTO EQUIPO VALUES (19,'RB Salzburgo',3);
INSERT INTO EQUIPO VALUES (20,'Olympiacos',3);
INSERT INTO EQUIPO VALUES (21,'Club Brujas',3);
INSERT INTO EQUIPO VALUES (22,'Valencia',3);
INSERT INTO EQUIPO VALUES (23,'Inter de Milán',3);
INSERT INTO EQUIPO VALUES (24,'Dinamo de Zagreb',3);

-- BOMBO 4 --
INSERT INTO EQUIPO VALUES (25,'Lokomotiv de Moscú',4);
INSERT INTO EQUIPO VALUES (26,'Estrella Roja',4);
INSERT INTO EQUIPO VALUES (27,'Genk',4);
INSERT INTO EQUIPO VALUES (28,'Galatasaray',4);
INSERT INTO EQUIPO VALUES (29,'RB Leipzig',4);
INSERT INTO EQUIPO VALUES (30,'Slavia Praga/Cluj',4);
INSERT INTO EQUIPO VALUES (31,'Atalanta',4);
INSERT INTO EQUIPO VALUES (32,'Lille',4);

COMMIT;
